# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  $puppet = <<PUPPET
    sudo dnf install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
    sudo dnf install -y puppet
PUPPET

  $modulesdb = <<MODULESDB
    puppet module install puppetlabs-firewall
    puppet module install puppetlabs/mysql
    sudo cp -vR ~/.puppetlabs/etc/code/modules/ /etc/puppetlabs/code/
MODULESDB

  # WEB - Debian 11
  config.vm.define "web" do |web|
    web.vm.box = "shekeriev/debian-11"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.89.151"
    web.vm.provision "shell", path: "add_hosts.sh"
    web.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo wget https://apt.puppet.com/puppet7-release-bullseye.deb -O repository.deb
    sudo dpkg -i repository.deb
    sudo apt-get install -y puppet
  SHELL

    web.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "web.pp"
      puppet.options = "--verbose --debug"
    end

    web.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 2
    end
  end

  # DB - CentOS Stream 8
  config.vm.define "db" do |db|
    db.vm.box = "shekeriev/centos-stream-8"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.89.152"
    db.vm.provision "shell", path: "add_hosts.sh"
    db.vm.provision "shell", inline: $puppet, privileged: false
    db.vm.provision "shell", inline: $modulesdb, privileged: false

    db.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "db.pp"
      puppet.options = "--verbose --debug"
    end

    db.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 2
    end
  end
  
end
